# This is a basic workflow to help you get started with Actions

name: Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - run: rm -rf .gitignore
      - name: Get clue-wasm
        run: ./get-wasm.sh
      - name: Build ace
        run: ./build-ace.sh
      - name: "Clean files not needed in the deployment"
        run: rm -rf ace-src Clue-wasm .gitmodules *.sh jsconfig.json
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
