name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache build
        uses: Swatinem/rust-cache@v1
      - name: "Build clue-wasm"
        run: ./build.sh
      - name: Deploy to GitHub Pages
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          rm -rf .gitignore
          git checkout -b gh-pages
          git reset --soft gh-pages
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f -A
          git commit --allow-empty -am "Deploy: $GITHUB_SHA"
          git push -f origin gh-pages
