name: Update submodules

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Update submodules"
        run: |
          git submodule init 
          git submodule update --remote --merge
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "$GITHUB_ACTOR"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Update submodules"
            git push
          fi
